### ISSUE TITLE
OnTopReplica dump bug, can’t fix need help 

### ISSUE THREAD

**Issue by maxbox0** [LorenzCK/OnTopReplica#33]
I have been having it reoccurring problem with on top replica in which it will not run the software it keeps giving me this dump file that I have gone in and deleted the listed name under the user several times in the software will still not run I do not know how to fix this I do not know if what I’m doing is correct I do not know how to look at the configuration logs or files do delete the right file.  Below is what it keeps telling me in the file that pops up... 

OnTopReplica Dump file
This file has been created because OnTopReplica crashed.
Please send it to lck@klopfenstein.net to help fix the bug that caused the crash.

Last exception:
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1. (C:\Users\Max Houston\AppData\Local\Lorenz_Cuno_Klopfenstein\OnTopReplica.exe_Url_khr4meaaowlk3gsw3kk45kduxnbvm1sn\3.5.1.0\user.config line 15) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at OnTopReplica.Properties.Settings.get_MustUpdate()
   at OnTopReplica.Program.Main(String[] args)

OnTopReplica v.3.5.1.0
OS: Microsoft Windows NT 6.2.9200.0
.NET: 4.0.30319.42000
DWM: True
Launch command: "C:\Users\Max Houston\AppData\Local\OnTopReplica\OnTopReplica.exe"
UTC time: 1/5/2018 12:20 PM

 I’ve done everything that I know of to do I’ve looked up videos unfortunately there are no videos onto how to fix this problem which is unbelievable I cannot believe nobody has had this problem before and has it posted a video about it but this is a very annoying problem and I cannot seem to get around it I cannot seem to fix it I have even uninstalled on top replica completely several times and nothing seems to work if anyone could post a small video and or very simple and very very easy instructions on how to fix this that would be much appreciated thank you.

**Comment by LorenzCK** [comment]
Hello @maxbox0,
as you mentioned, this is a known issue that will be fixed in the near future. In the meantime, you just need to delete the configuration file mentioned in the crash log.

In order to do so, the easiest way is to open the command line interface (that is, right-click on the Windows Start button and click on "Powershell" or "Command prompt"). This should open a command line window. Copy the following command and hit [Enter]:

```
del "C:\Users\Max Houston\AppData\Local\Lorenz_Cuno_Klopfenstein\OnTopReplica.exe_Url_khr4meaaowlk3gs
w3kk45kduxnbvm1sn\3.5.1.0\user.config"
```

This will delete the configuration file and OnTopReplica should be able to start again. Let me know whether this works or not.

**Comment by maxbox0** [comment]
I did  exactly what she told me I was able to pull up the command prompt and I  copy and paste did exactly what you told me to same problem nothings changed nothings got deleted it tells me that it is not able to find that certain file him and I still have the same problem unresolved and not fixed...

**Comment by LorenzCK** [comment]
This is strange. Then I would suggest to open the
`C:\Users\Max Houston\AppData\Local\Lorenz_Cuno_Klopfenstein`
folder (by pasting it into Windows search or the Windows Explorer address bar. Try deleting everything in that folder and launching the application again.
