### ISSUE TITLE
OnTopReplica not working unless i switch to admin account 

### ISSUE THREAD

**Issue by SBSomething** [LorenzCK/OnTopReplica#5]
Hello, I have been a frequent user of ontopreplica over the past year and I love your software. However, recently I have been unable to launch it, if I click the short cut I get this error 

`OnTopReplica Dump file
This file has been created because OnTopReplica crashed.
Please send it to lck@klopfenstein.net to help fix the bug that caused the crash.

Last exception:
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1. (C:\Users\Krish_v97ezyc\AppData\Local\Lorenz_Cuno_Klopfenstein\OnTopReplica.exe_Url_egi52m5aidk1onh4og0tkviyei5d0guz\3.5.1.0\user.config line 15) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at OnTopReplica.Properties.Settings.get_MustUpdate()
   at OnTopReplica.Program.Main(String[] args)

OnTopReplica v.3.5.1.0
OS: Microsoft Windows NT 6.2.9200.0
.NET: 4.0.30319.42000
DWM: True`

If I try running as admin from a standard user account, I do not even recieve a dump file, it simply does not launch. The only way the software runs is if I install it on an admin-level account, and run it on that account. Please fix this issue, thank you! 
[OnTopReplica-dump-201767-161.txt](https://github.com/LorenzCK/OnTopReplica/files/1065881/OnTopReplica-dump-201767-161.txt)

**Comment by LorenzCK** [comment]
Hi @SBSomething,
this is a known bug due to the corruption of the configuration file. You can fix it just by deleting the `C:\Users\Krish_v97ezyc\AppData\Local\Lorenz_Cuno_Klopfenstein\OnTopReplica.exe_Url_egi52m5aidk1onh4og0tkviyei5d0guz\3.5.1.0\user.config` file mentioned in the log file. This will reset OnTopReplica and the application should be able to start again with your standard user account. Let me know if this works for you.
The underlying issue will be fixed in the next version.
