### ISSUE TITLE
Application no longer opens

### ISSUE THREAD

**Issue by Stealthic** [LorenzCK/OnTopReplica#83]
The application won't open anymore in Windows 10. I haven't updated windows nor ontop. I click to open the .exe in both regular and administrator and nothing happens with nothing running in task manager. Is this a common issue with a possible fix?

**Comment by LorenzCK** [comment]
When OnTopReplica crashes, it should generate a crash report (a text file) on the user's desktop: can you check if there are any files with more information?

**Comment by RyanD** [comment]
I don't think its a hard crash, I think the settings window just appears for a second and becomes invisible, I still see it (albeit distorted) in the task bar hover. 
![2019-04-30 18_03_55-Window](https://user-images.githubusercontent.com/163866/56996401-6d8e5900-6b72-11e9-97ad-dc1ae530d7b6.png)

**Comment by Stealthic** [comment]
Crash report:

OnTopReplica Dump file
This file has been created because OnTopReplica crashed.
Please send it to lck@klopfenstein.net to help fix the bug that caused the crash.

Last exception:
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1. (C:\Users\Hunte\AppData\Local\Lorenz_Cuno_Klopfenstein\OnTopReplica.exe_Url_rzgqv5qwygenk4czm3xhun0quvgyolek\3.5.1.0\user.config line 15) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at OnTopReplica.Properties.Settings.get_MustUpdate()
   at OnTopReplica.Program.Main(String[] args)

Last log entries:
01:17:00 Launching OnTopReplica v.3.5.1.0
01:17:00 Microsoft Windows NT 10.0.17134.0 detected, using support class OnTopReplica.Platforms.WindowsSeven
01:17:00 Platform support initialized
01:17:00 Unhandled exception
         System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1. (C:\Users\Hunte\AppData\Local\Lorenz_Cuno_Klopfenstein\OnTopReplica.exe_Url_rzgqv5qwygenk4czm3xhun0quvgyolek\3.5.1.0\user.config line 15) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at OnTopReplica.Properties.Settings.get_MustUpdate()
   at OnTopReplica.Program.Main(String[] args)

OnTopReplica v.3.5.1.0
OS: Microsoft Windows NT 10.0.17134.0
.NET: 4.0.30319.42000
DWM: True
Launch command: "C:\Program Files (x86)\OnTopReplica\OnTopReplica\OnTopReplica.exe" 
UTC time: 4/30/2019 6:17 AM

**Comment by LorenzCK** [comment]
@Stealthic: OK, this is a known issue when the configuration file becomes corrupted. Please just delete the file `C:\Users\Hunte\AppData\Local\Lorenz_Cuno_Klopfenstein\OnTopReplica.exe_Url_rzgqv5qwygenk4czm3xhun0quvgyolek\3.5.1.0\user.config` and OnTopReplica should start again.

@RyanD: not sure about that issue, is the OnTopReplica window hidden somewhere off-screen? Perhaps you can try to reset the application by deleting the application's configuration files (also somewhere under `C:\Users\<USERNAME>\AppData\Local\Lorenz_Cuno_Klopfenstein`).

**Comment by RyanD** [comment]
@LorenzCK Trashing the prefs file did the trick! Not sure what I did, except I did get a new 4K monitor that moved all my screens around.. maybe that had something to do with it?

**Comment by LorenzCK** [comment]
@RyanD: great, happy to hear that. Not sure about why that happens. Did you perhaps start multiple instances of the application at the same time? That's one of the few ways I can imagine that settings file corruption might be caused.

**Comment by RyanD** [comment]
Oooh that could be! 😊
